import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Navbar'
import { cn } from '@nextui-org/react'
import Providers from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={cn(
      'antialiased dark',
      inter.className
    )}>

    <body className='min-h-screen antialiased'>
        <NavBar />

        <Providers>{children}</Providers>

        </body>
    </html>
  )
}
